# Understanding Indices and Contractions

- [Tensors.net turotial 1](https://www.tensors.net/j-tutorial-1)
- [ITensor examples](https://docs.itensor.org/ITensors/stable/examples/ITensor.html)


In [ ]:
# Let's do this first with base Julia
using LinearAlgebra

In [9]:
# tensor with randomly generated entries
# order 3, dims: 2-by-3-by-4
A = rand(2, 3, 4);
  
display(A)

2×3×4 Array{Float64, 3}:
[:, :, 1] =
 0.361687  0.984131  0.97569
 0.374929  0.731104  0.781717

[:, :, 2] =
 0.795034  0.838338  0.723459
 0.882422  0.719135  0.54657

[:, :, 3] =
 0.855455  0.898681  0.728976
 0.459506  0.405577  0.106074

[:, :, 4] =
 0.555768  0.920949  0.95651
 0.816655  0.337895  0.280329

Order : defined as the number of indices a tensor has

Eg: 3 indices are required to specify each entry of A. Thus, A is a tensor of order 3.

In [10]:
# identity matrix, order 2, dims: 5-by-5 (New syntax in Julia 0.7+)
B_int = Matrix{Int64}(I, 5, 5);
B_float = Matrix{Float64}(I, 5, 5);
display(B_int)
display(B_float)

5×5 Matrix{Int64}:
 1  0  0  0  0
 0  1  0  0  0
 0  0  1  0  0
 0  0  0  1  0
 0  0  0  0  1

5×5 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [11]:
# matrix of 0's, order 2, dims: 3-by-5
D = zeros(3, 5);
display(D)

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [12]:
# initialize complex random tensor
E = rand(2, 3) + im * rand(2, 3);
display(E)

2×3 Matrix{ComplexF64}:
 0.435297+0.106668im  0.498568+0.415215im  0.526393+0.921931im
 0.318349+0.601693im  0.475443+0.37428im   0.119638+0.495661im

In [13]:
# creating column vectors (default)
col_vec = [0.2, 0.5, 0.3];
rand_col_vec = rand(3);
display(col_vec)
display(rand_col_vec)

3-element Vector{Float64}:
 0.2
 0.5
 0.3

3-element Vector{Float64}:
 0.7767021878644119
 0.3155148531069042
 0.9051371193420624

In [14]:
# creating row vectors
# notice the absence of commas between the entries
row_vec = [0.2 0.5 0.3];
display(row_vec)

1×3 Matrix{Float64}:
 0.2  0.5  0.3

In [15]:
# stacking two column vectors horizontally
stacked_hcol_vec = [col_vec rand_col_vec]; # we are creating a "row vector" of with elements col_vec and rand_col_vec
display(stacked_hcol_vec)
@show size(stacked_hcol_vec);
@show ndims(stacked_hcol_vec);
@show length(stacked_hcol_vec); # number of entries in the vector

3×2 Matrix{Float64}:
 0.2  0.776702
 0.5  0.315515
 0.3  0.905137

size(stacked_hcol_vec) = (3, 2)
ndims(stacked_hcol_vec) = 2
length(stacked_hcol_vec) = 6


In [16]:
# stacking two column vectors vertically. Note the shape and dimensions of the result
stacked_vcol_vec = [col_vec, rand_col_vec];
display(stacked_vcol_vec)
@show size(stacked_vcol_vec);
@show ndims(stacked_vcol_vec);
@show length(stacked_vcol_vec); # number of entries in the vector

2-element Vector{Vector{Float64}}:
 [0.2, 0.5, 0.3]
 [0.7767021878644119, 0.3155148531069042, 0.9051371193420624]

size(stacked_vcol_vec) = (2,)
ndims(stacked_vcol_vec) = 1
length(stacked_vcol_vec) = 2


In [17]:
# stacking the elements of two column vectors vertically. Note the shape and dimensions of the result
stacked_vcol_vec_el = [col_vec; rand_col_vec]; # the ; between the elements to stack the elements 
display(stacked_vcol_vec_el)
@show size(stacked_vcol_vec_el);
@show ndims(stacked_vcol_vec_el);
@show length(stacked_vcol_vec_el); # number of entries in the vector

6-element Vector{Float64}:
 0.2
 0.5
 0.3
 0.7767021878644119
 0.3155148531069042
 0.9051371193420624

size(stacked_vcol_vec_el) = (6,)
ndims(stacked_vcol_vec_el) = 1
length(stacked_vcol_vec_el) = 6


In [18]:
# practice :  create Pauli matrices by specifying the entries going column-wise unlike Numpy 
sigma_x = [[0,1.0] [ 1.0,0]];
sigma_y = [[0.0, im] [-im,0.0]];
sigma_z = [[1.0,0] [0,-1.0]];
display(sigma_x)
display(sigma_y)
display(sigma_z)

2×2 Matrix{Float64}:
 0.0  1.0
 1.0  0.0

2×2 Matrix{ComplexF64}:
 0.0+0.0im  0.0-1.0im
 0.0+1.0im  0.0+0.0im

2×2 Matrix{Float64}:
 1.0   0.0
 0.0  -1.0

In [75]:
# tensor of 1's, order 4, dims: 3 x 4 x 2 x 1
C = ones(3, 4, 2, 1);
display(C); # notice how the tensor is displayed. it will print higher order tensors as slices across the dimensions

3×4×2×1 Array{Float64, 4}:
[:, :, 1, 1] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 2, 1] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [76]:
# Permute allows the index ordering of a tensor to be changed (but does not change the number of indices).
A_ijkl = rand(4, 4, 4, 4);
A_lijk = permutedims(A_ijkl, [4, 1, 2, 3]);
display(A_ijkl);
display(A_lijk);

4×4×4×4 Array{Float64, 4}:
[:, :, 1, 1] =
 0.725398   0.11443   0.864363  0.176485
 0.0591615  0.29647   0.642579  0.64068
 0.276246   0.461338  0.190902  0.277306
 0.726484   0.231104  0.121066  0.82437

[:, :, 2, 1] =
 0.561419   0.780625  0.965521  0.368285
 0.275962   0.255924  0.877772  0.806507
 0.0110242  0.447362  0.716733  0.501692
 0.658458   0.598032  0.616706  0.566022

[:, :, 3, 1] =
 0.316589   0.621014  0.980531  0.649236
 0.940182   0.177339  0.421381  0.844636
 0.0837961  0.550121  0.429238  0.236832
 0.817258   0.823858  0.779691  0.187101

[:, :, 4, 1] =
 0.869951   0.833123  0.781388  0.406093
 0.94658    0.545995  0.14768   0.56926
 0.698597   0.307771  0.836137  0.904346
 0.0739226  0.334207  0.642116  0.850886

[:, :, 1, 2] =
 0.200216  0.113195   0.937747   0.131064
 0.454938  0.251827   0.770698   0.193061
 0.414882  0.0305185  0.211544   0.761078
 0.583816  0.882862   0.0873485  0.817465

[:, :, 2, 2] =
 0.0393635  0.648233   0.448178   0.749394
 0.548026   0.

4×4×4×4 Array{Float64, 4}:
[:, :, 1, 1] =
 0.725398  0.0591615  0.276246  0.726484
 0.200216  0.454938   0.414882  0.583816
 0.622387  0.627157   0.213357  0.955984
 0.696034  0.511046   0.529592  0.48594

[:, :, 2, 1] =
 0.11443   0.29647   0.461338   0.231104
 0.113195  0.251827  0.0305185  0.882862
 0.541061  0.373132  0.314338   0.218397
 0.304262  0.377433  0.846552   0.439535

[:, :, 3, 1] =
 0.864363  0.642579  0.190902  0.121066
 0.937747  0.770698  0.211544  0.0873485
 0.572476  0.899659  0.518022  0.304646
 0.200327  0.158814  0.536743  0.469052

[:, :, 4, 1] =
 0.176485  0.64068   0.277306  0.82437
 0.131064  0.193061  0.761078  0.817465
 0.955056  0.453433  0.101707  0.866988
 0.158772  0.936931  0.898761  0.878627

[:, :, 1, 2] =
 0.561419   0.275962  0.0110242  0.658458
 0.0393635  0.548026  0.405419   0.343061
 0.399062   0.558779  0.804307   0.0650709
 0.998354   0.36914   0.260971   0.69473

[:, :, 2, 2] =
 0.780625  0.255924     0.447362  0.598032
 0.648233  0.858823 

In [ ]:
# The reshape function which allows a collection of tensor indices to be combined into a single larger index (or vice-versa), thus can change the number of indices but not the total dimension.
B = rand(3, 3, 3);
Btilda = reshape(B, 3, 3^2);

## Contractions

The usefulness of permute and reshape functions is that they allow a contraction between a pair of tensors (which we call a binary tensor contraction) to be recast as a matrix multiplication. Although the computational cost (measured in number of scalar multiplications) is the same both ways, it is usually preferable to recast as multiplication as modern hardware performs vectorized operations much faster than when using the equivalent FOR loop.

In [7]:
d = 3;
A = rand(d, d, d, d);
B = rand(d, d, d, d);

display(A);
display(B);



3×3×3×3 Array{Float64, 4}:
[:, :, 1, 1] =
 0.157951  0.302612  0.324461
 0.202763  0.238774  0.95933
 0.278204  0.656736  0.317213

[:, :, 2, 1] =
 0.42903   0.309848  0.113033
 0.403128  0.268497  0.257314
 0.378227  0.861558  0.940296

[:, :, 3, 1] =
 0.836167   0.972739  0.791949
 0.0198137  0.708423  0.704877
 0.776402   0.874331  0.202575

[:, :, 1, 2] =
 0.788784  0.267395  0.435637
 0.511267  0.827793  0.365361
 0.373076  0.588904  0.585086

[:, :, 2, 2] =
 0.259948   0.248509  0.0870907
 0.0965671  0.411664  0.201554
 0.605918   0.613597  0.681582

[:, :, 3, 2] =
 0.697085  0.654733  0.511889
 0.320466  0.847857  0.815523
 0.375699  0.153711  0.00759904

[:, :, 1, 3] =
 0.18431   0.307831  0.0427473
 0.841408  0.89689   0.424711
 0.648904  0.731198  0.876458

[:, :, 2, 3] =
 0.539464  0.0777223  0.0619976
 0.870399  0.706027   0.506327
 0.772481  0.451792   0.771032

[:, :, 3, 3] =
 0.777772  0.208754  0.369296
 0.778169  0.544205  0.00414384
 0.988361  0.55783   0.210101

3×3×3×3 Array{Float64, 4}:
[:, :, 1, 1] =
 0.466165   0.388485   0.875122
 0.576915   0.287681   0.869027
 0.0538182  0.0938959  0.625866

[:, :, 2, 1] =
 0.840264  0.541047  0.404416
 0.397355  0.335173  0.629468
 0.15414   0.106716  0.418002

[:, :, 3, 1] =
 0.586718  0.869541  0.47709
 0.478851  0.474982  0.566784
 0.876389  0.46678   0.771794

[:, :, 1, 2] =
 0.649425   0.0892967  0.173319
 0.0667822  0.94007    0.526679
 0.193418   0.329412   0.384464

[:, :, 2, 2] =
 0.262567   0.39624   0.781325
 0.0473457  0.658665  0.43926
 0.278182   0.358527  0.971752

[:, :, 3, 2] =
 0.682582  0.810999  0.585379
 0.279191  0.724058  0.373432
 0.977893  0.885756  0.102482

[:, :, 1, 3] =
 0.523664  0.930789  0.450019
 0.195691  0.471503  0.362631
 0.698382  0.242067  0.411586

[:, :, 2, 3] =
 0.549913  0.594406  0.387626
 0.207052  0.249468  0.916769
 0.477435  0.527591  0.0251548

[:, :, 3, 3] =
 0.478036  0.646553  0.849965
 0.144906  0.509976  0.391718
 0.231057  0.317896  0.571144

In [8]:
# Contraction example : C_ijkl = A_imjn * B_mkln

# Simple Julia
Ap = permutedims(A, [1, 3, 2, 4]); # imjn -> ijmn
Bp = permutedims(B, [1, 4, 2, 3]); # mkln -> mnkl
App = reshape(Ap, d^2, d^2);
Bpp = reshape(Bp, d^2, d^2);
Cpp = App * Bpp;
C = reshape(Cpp, d, d, d, d);
display(C)

3×3×3×3 Array{Float64, 4}:
[:, :, 1, 1] =
 1.06666  0.9281   2.29509
 1.65462  1.43343  1.39524
 2.01542  2.32168  1.90643

[:, :, 2, 1] =
 0.971236  1.10572  2.43717
 2.4906    1.98564  2.35389
 2.26737   2.45721  1.98655

[:, :, 3, 1] =
 1.26147  1.22136  3.3129
 2.52911  1.91432  2.43901
 2.5304   3.18725  2.44858

[:, :, 1, 2] =
 0.829433  0.947639  2.21487
 1.53937   1.45257   1.30053
 1.75891   2.0693    1.89839

[:, :, 2, 2] =
 1.07527  1.01871  2.46317
 2.11888  1.67787  1.9017
 2.18051  2.46103  1.82507

[:, :, 3, 2] =
 1.9018   1.09461  3.11333
 2.9105   1.88913  2.96454
 2.72115  3.22662  2.21728

[:, :, 1, 3] =
 1.70359  1.1146   3.29701
 2.64175  1.60393  2.67336
 2.3656   3.32284  1.96038

[:, :, 2, 3] =
 1.94145  1.44902  3.77832
 3.21157  2.23686  3.06087
 3.02019  3.69137  2.59798

[:, :, 3, 3] =
 1.40518  1.24582  3.22027
 2.92739  2.07957  2.41974
 2.5866   3.32209  2.479

In [ ]:
# The same example but using ITensors
using ITensors
using ITensorUnicodePlots
# using GLMakie
# using ITensorMakie


In [10]:

# Use the Let block : code written in the Julia global scope can have some surprising behaviors. Putting your code into a let block avoids these issues
let 
    # open indices of A_imjn
    i = Index(d, "i");
    j = Index(d, "j");
    
    # open indices of B_mkln
    k = Index(d, "k");
    l = Index(d, "l");
    
    # contracted indices
    m = Index(d, "m");
    n = Index(d, "n");


    # create the tensors with the appropriate labels
    A_ITensor = ITensor(A, i, m, j, n);
    B_ITensor = ITensor(B, m, k, l, n);

    # Contract over shared indices m and n
    C_ITensor = @visualize A_ITensor * B_ITensor edge_labels = (tags=true,);

    # if our contraction is correct, the resulting tensor C should have open indices i, j, k, l
    @show inds(C_ITensor);


    # convert the C_ITensor to a regular Julia array and check that it matches the result from simple Julia
    C_ITensor_arr = Array(C_ITensor,i,j,k,l);

    @show (C_ITensor_arr ≈ C);
end


    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀B_ITensor⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠔⠉⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠤⠒⠁⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⠔⠊⠁⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠔⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠤⠒⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀(3|"m")⊗(3|"n")⠀⠀⠀⠀⠀(3|"k")⊗(3|"⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠔⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠤⠒⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⠔⠊⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠔⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠤⠒⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⠀⠀⠀⠀⠀ 
    ⠀⠀⠀⠀⠀⠀⣀⠤⠊⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
    ⠀A_ITensor

inds(C_ITensor) = ((dim=3|id=174|"i"), (dim=3|id=708|"j"), (dim=3|id=53|"k"), (dim=3|id=30|"l"))
C_ITensor_arr ≈ C = true


true